### ISSUE TITLE
S3AclSource

### ISSUE THREAD

**Issue by simplesteph** [simplesteph/kafka-security-manager#13]
Thumbs up if you want this feature, PR welcome

**Comment by dkulig** [comment]
I'd love to see an S3 source plugin. Let me know if you need any help

**Comment by simplesteph** [comment]
@dkulig please feel free to implement a PR I'll be happy to provide some feedback

**Comment by simplesteph** [comment]
hi @dkulig ! did you make any progress on this? Would love to have you as a contributor

**Comment by silverbadge** [comment]
I've submitted a PR to enable this feature. Tested and updated the docs. Questions and feedback are welcome on https://github.com/simplesteph/kafka-security-manager/pull/27
