### ISSUE TITLE
Support Kafka 2 ACL format

### ISSUE THREAD

**Issue by silverbadge** [simplesteph/kafka-security-manager#28]
Kafka 2 now supports `prefixed` and `literal` resource pattern [KAFKA-6841](https://issues.apache.org/jira/browse/KAFKA-6841). This currently working with default value for Kafka 2 of literal. It would be great to get KSM to support both using a new column `resource-pattern` in the input csv file so topics ACLs can be suffixed with wildcards when the `resource-pattern` is `prefixed`

**Comment by simplesteph** [comment]
Good point! Wanna try out a PR ? 
The change has to be backwards compatible with current version that's all
