### ISSUE TITLE
Question CSV Multipe Operation possible?

### ISSUE THREAD

**Issue by densanki** [simplesteph/kafka-security-manager#31]
Hi,

is it possible to write multiple operations on same acl line on csv format as on the json version?

Example
Normal Example with Write, Describe and Read Operations
`"User:CN=Test",Topic,ClientTopic,Write,Allow,*
"User:CN=Test",Topic,ClientTopic,Describe,Allow,*
"User:CN=Test",Topic,ClientTopic,Read,Allow,*`

Is it possible to write multiple operations on same line? 
`"User:CN=Test",Topic,ClientTopic,Write;Describe;Read,Allow,*`

Json Example where it is possible:
`{
	"version": 1,
	"acls": [{
		"principals": ["user:alice”, "group: kafka-devs"],
		"permissionType": "ALLOW",
		"operations": [ "READ", "WRITE" ],
		"hosts": ["host1", "host2" ]
	}]
}
`

**(Edit by Stephane): Thumbs up or down based on if you want this feature**

**Comment by simplesteph** [comment]
It's possible to implement this but can become potentially super messy. 
Besides just having more lines in your file, is something else a problem driving this change?

**Comment by simplesteph** [comment]
It's now possible to create your own implementation of `AclParser` to accomodate for any format that you want (not just CSV). I'll accept contributions on AclParser as forms of PR, but for now this solves your issue
