### ISSUE TITLE
Official release for Kafka v2.0.0 support

### ISSUE THREAD

**Issue by vultron81** [simplesteph/kafka-security-manager#33]
Can you create an official release v0.4 and Docker image for your [commit](https://github.com/simplesteph/kafka-security-manager/commit/da7420cf06dddd39bf89b5a53d810afc828b0e7b) that added support for Kafka v2.0.0?

**Comment by simplesteph** [comment]
yes! Can you please test `latest`, make sure it works for your use case, maybe let's bundle in #34 if we have a chance, then I'll make a release for 0.4 - Kafka 2.0.0

**Comment by vultron81** [comment]
Thank you for creating this service!  It saved our ass when we had to implement SSL in Kafka for PCI compliance.

**Comment by simplesteph** [comment]
Pleased to have helped!

**Comment by simplesteph** [comment]
Done as per https://github.com/simplesteph/kafka-security-manager/commit/661e41d6af6ae6f8511f2e1428063e16a87695c6

Docker info:
Tag: v0.4-release
Size: 123 MB (thanks for the big reduction in size!)
