### ISSUE TITLE
Idea: support for connecting to multiple Zookeeper nodes

### ISSUE THREAD

**Issue by cruscio** [simplesteph/kafka-security-manager#43]
Current design requires specifying a single zookeeper node that the Kafka Security Manager service will connect to. It'd be nice if the configuration allowed for a list and rotation logic to handle when a  zookeeper node was unavailable due to maintenance/outage. 

Alternatively, how about a configuration where multiple Kafka Security Managers are run; one on each zookeeper node? And use Zookeeper to perform leader election. Only the leader instance of Kafka Security Manager would apply ACLs; others would sit idle. Any ZK/KSM node could be taken offline at any time and a new leader would be elected - there'd be no disruption of either ZooKeeper or Kafka Security Manager service.

**Comment by simplesteph** [comment]
You can 100% specify a list of zookeeper for KSM: `zoo1:2181,zoo2:2181,zoo3:2181/kafka`
Are you not seeing this working?

Otherwise, I agree running KSM in highly available mode would be nice. If you want to work on a PR I'll happily review it

**Comment by cruscio** [comment]
Ahh, thanks for clarifying that. I couldn't find any examples of that in the repo and didn't realize `zookeeper connection string` in the description of `AUTHORIZER_ZOOKEEPER_CONNECT` was a reference to [this](https://zookeeper.apache.org/doc/r3.4.13/api/org/apache/zookeeper/ZooKeeper.html#ZooKeeper(java.lang.String ) (just dug a little deeper after reading your reply)

> To create a ZooKeeper client object, the application needs to pass a connection string containing a comma separated list of host:port pairs, each corresponding to a ZooKeeper server.

I'm new to Kafka & ZooKeeper. Still have a lot to learn.
