### ISSUE TITLE
link to API swagger document does not exist - src/main/resources/specs/KsmService.yml

### ISSUE THREAD

**Issue by adaddy1975** [simplesteph/kafka-security-manager#46]
link to API swagger document does not exist - src/main/resources/specs/KsmService.yml

**Comment by simplesteph** [comment]
You would have to generate it when you build the project. 

I'm curious, what are you trying to achieve, build a UI?

**Comment by adaddy1975** [comment]
Yes, might look at building a UI so i was trying to see which API are currently exposed

**Comment by simplesteph** [comment]
Awesome! 

Run 
```
sbt clean test
sbt universal:stage
```

It should generate the Swagger and you can start playing with the UI. Can't wait to see what you come up with!
