### ISSUE TITLE
`EXTRACT` should be `KSM_EXTRACT` in README

### ISSUE THREAD

**Issue by kentso** [simplesteph/kafka-security-manager#47]
Hello,

I found that in the [Example](https://github.com/simplesteph/kafka-security-manager/blob/master/README.md#running) and [Extracting ACLs](https://github.com/simplesteph/kafka-security-manager/blob/master/README.md#extracting-acls), `EXTRACT` should actually be `KSM_EXTRACT` according to the configuration setting below.

Reference:
https://github.com/simplesteph/kafka-security-manager/blob/d3a9a60219996e2b70d8a78424b41b8947a0784b/src/main/resources/application.conf#L7

**Comment by simplesteph** [comment]
fixed by #48
