### ISSUE TITLE
The input line is too long. The syntax of the command is incorrect error using kafka-security-manager.bat

### ISSUE THREAD

**Issue by shayaantx** [simplesteph/kafka-security-manager#55]
I get this error "The input line is too long. The syntax of the command is incorrect" using kafka-security-manager.bat unless I put the binary at the root of my drive on windows 10.

I fixed it by shortening the classpath using a wildcard, see below.

set "APP_CLASSPATH=%APP_LIB_DIR%\com.github.simplesteph.....

to

set "APP_CLASSPATH=%APP_LIB_DIR%/*"

**Comment by simplesteph** [comment]
hmmm if there's a fix for this, happy to accept a PR. The executables are generated using a sbt plugin

**Comment by shayaantx** [comment]
here ya go, https://github.com/simplesteph/kafka-security-manager/pull/60

**Comment by simplesteph** [comment]
solved by #60
