### ISSUE TITLE
Stop KSM after one run

### ISSUE THREAD

**Issue by georgpet** [simplesteph/kafka-security-manager#56]
Hi Stephane,

is there any way how to tell to KSM to stop after the first processing/execution of the ACL?
We want to use external trigger to start KSM (e.g. Github merge to Master or S3 file upload) and then stop it in order to safe the costs.

Would it be possible to add this feature, if it doesn't exist  yet?

Thanks and regards,
Petros

**Comment by simplesteph** [comment]
Hi

You're more than welcome to do a PR for it, it shouldn't be too hard!

Cheers

Stephane

**Comment by georgpet** [comment]
Hi Stephane,

fair enough, I'm going to have a look and will try to propose the change via PR.

Best regards,
Petros

**Comment by simplesteph** [comment]
Keeping this open while the PR is being implemented

**Comment by simplesteph** [comment]
closed by #57
