### ISSUE TITLE
Fail to connect to bitbucket as the resource.

### ISSUE THREAD

**Issue by michellewen1516** [simplesteph/kafka-security-manager#68]
Hi Stephane,

I always got the error of "WARN Too many invalid password attempts. Log in at https://id.atlassian.com/ to restore access." When I use bitbucket as my resource. The user name is just my user name, and I created an APP password as the password.  I used bitbucket cloud. Do you have any idea about my problem? Thanks

**Comment by simplesteph** [comment]
No idea, I had coded that a while back and it was working. I suggest looking at the implementation and the API doc

**Comment by michellewen1516** [comment]
Thanks for your quick reply. There are bitbucket server and bitbucket cloud. Do both of them are supported?

**Comment by simplesteph** [comment]
Bitbucket Server, I"m not sure if BitBucket cloud is the same API.
This is a non commercial open source project, if you can do a PR with a working module that'd be awesome. It shouldn't be too hard :)

**Comment by michellewen1516** [comment]
Hi Stephane,
I'd like to push a branch with bitbucket cloud source, but I got this error:
remote: Permission to simplesteph/kafka-security-manager.git denied to michellewen1516.

Please take a look at what should I do for that.   Thanks a lot.

**Comment by simplesteph** [comment]
This will help you: https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by michellewen1516** [comment]
Thanks.

**Comment by simplesteph** [comment]
closed by https://github.com/simplesteph/kafka-security-manager/pull/69
