### ISSUE TITLE
Bitbucket Cloud config required despite not being used

### ISSUE THREAD

**Issue by nonki** [simplesteph/kafka-security-manager#70]
Our KSM deployments use `com.github.simplesteph.ksm.source.BitbucketServerSourceAcl` as we have a private Bitbucket deployment.

However, now our KSM apps running on `:latest` are failing to startup due to:

`Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: application.conf @ jar:file:/opt/docker/lib/com.github.simplesteph.ksm.kafka-security-manager-0.9-SNAPSHOT.jar!/application.conf: 115: Could not resolve substitution to a value: ${SOURCE_BITBUCKET_CLOUD_AUTH_PASSWORD}
`

Seems this config is weirdly required even though we don't use the cloud source ACL type.

I guess due to https://github.com/simplesteph/kafka-security-manager/blob/master/src/main/resources/application.conf#L114-L115

All other ENV checks are optional other than these.

**Comment by simplesteph** [comment]
Good point, I've fixed it, should be alright after the CICD runs. Let me know and then close the issue
