### ISSUE TITLE
No Way to Override the additional properties like ssl.endpoint.identification.algorithm

### ISSUE THREAD

**Issue by sbavi2** [simplesteph/kafka-security-manager#80]
It would be good if there is a way to override additional parameters in ADMIN CLIENT properties other than the standard offered. Im facing issues overriding the ssl.enabled.protocols and ssl.endpoint.identification.algorithm

**Comment by simplesteph** [comment]
yes you can. Just add the missing property in the conf file and it will be automatically picked up

edit the config here:
https://github.com/simplesteph/kafka-security-manager/blob/master/src/main/resources/application.conf#L39

and it will be picked up by this code
https://github.com/simplesteph/kafka-security-manager/blob/31f9325e00a8736b784d979ae9cf8e50396d20e9/src/main/scala/com/github/simplesteph/ksm/AppConfig.scala#L19-L30
